import {
  Atom,
  BookOpen,
  Brain,
  Calculator,
  Earth,
  FlaskConical,
  Lightbulb,
  Swords,
  Trees,
} from "lucide-react";
import { Lesson, TytLessonName } from "./types";

export const tytLessons: Record<TytLessonName, Lesson> = {
  Türkçe: {
    name: `Türkçe`,
    totalQuestions: 40,
    icon: BookOpen,
    bgClass: "bg-amber-100 dark:bg-amber-900/20",
    iconColor: "text-amber-700 dark:text-amber-300",
    topics: [
      "Sözcükte Anlam",
      "Söz Yorumu",
      "Deyim ve Atasözü",
      "Cümlede Anlam",
      "Paragraf",
      "Paragrafta Anlatım Teknikleri",
      "Paragrafta Düşünceyi Geliştirme Yolları",
      "Paragrafta Yapı",
      "Paragrafta Konu-Ana Düşünce",
      "Paragrafta Yardımcı Düşünce",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcükte Yapı/Ekler",
      "Sözcük Türleri",
      "İsimler",
      "Zamirler",
      "Sıfatlar",
      "Zarflar",
      "Edat – Bağlaç – Ünlem",
      "Fiiller",
      "Fiilde Anlam (Kip-Kişi-Yapı)",
      "Ek Fiil",
      "Fiilimsi",
      "Fiilde Çatı",
      "Sözcük Grupları",
      "Cümlenin Ögeleri",
      "Cümle Türleri",
      "Anlatım Bozukluğu",
    ],
  },
  Tarih: {
    name: `Tarih`,
    totalQuestions: 5,
    icon: Swords,
    bgClass: "bg-rose-100 dark:bg-rose-900/20",
    iconColor: "text-rose-700 dark:text-rose-300",
    topics: [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "Orta Çağ’da Dünya",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu",
      "Türklerin İslamiyet’i Kabulü ve İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti",
      "Devletleşme Sürecinde Savaşçılar ve Askerler",
      "Beylikten Devlete Osmanlı Medeniyeti",
      "Dünya Gücü Osmanlı",
      "Sultan ve Osmanlı Merkez Teşkilatı",
      "Klasik Çağda Osmanlı Toplum Düzeni",
      "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
      "Değişim Çağında Avrupa ve Osmanlı",
      "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
      "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
      "Sermaye ve Emek",
      "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
      "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
      "Milli Mücadele",
      "Atatürkçülük ve Türk İnkılabı",
    ],
  },
  Coğrafya: {
    name: "Coğrafya",
    totalQuestions: 5,
    icon: Earth,
    bgClass: "bg-sky-100 dark:bg-sky-900/20",
    iconColor: "text-sky-700 dark:text-sky-300",
    topics: [
      "Doğa ve İnsan",
      "Dünya’nın Şekli ve Hareketleri",
      "Coğrafi Konum",
      "Harita Bilgisi",
      "Atmosfer ve Sıcaklık",
      "İklimler",
      "Basınç ve Rüzgarlar",
      "Nem, Yağış ve Buharlaşma",
      "İç Kuvvetler / Dış Kuvvetler",
      "Su – Toprak ve Bitkiler",
      "Nüfus",
      "Göç",
      "Yerleşme",
      "Türkiye’nin Yer Şekilleri",
      "Ekonomik Faaliyetler",
      "Bölgeler",
      "Uluslararası Ulaşım Hatları",
      "Çevre ve Toplum",
      "Doğal Afetler",
    ],
  },
  Felsefe: {
    name: "Felsefe",
    totalQuestions: 5,
    icon: Lightbulb,
    bgClass: "bg-violet-100 dark:bg-violet-900/20",
    iconColor: "text-violet-700 dark:text-violet-300",
    topics: [
      "Felsefe’nin Konusu",
      "Bilgi Felsefesi",
      "Varlık Felsefesi",
      "Ahlak Felsefesi",
      "Sanat Felsefesi",
      "Din Felsefesi",
      "Siyaset Felsefesi",
      "Bilim Felsefesi",
      "İlk Çağ Felsefesi",
      "2. Yüzyıl ve 15. Yüzyıl Felsefeleri",
      "15. Yüzyıl ve 17. Yüzyıl Felsefeleri",
      "18. Yüzyıl ve 19. Yüzyıl Felsefeleri",
      "20. Yüzyıl Felsefesi",
    ],
  },
  "Din Kültürü": {
    name: "Din Kültürü",
    totalQuestions: 5,
    icon: Brain,
    bgClass: "bg-emerald-100 dark:bg-emerald-900/20",
    iconColor: "text-emerald-700 dark:text-emerald-300",
    topics: [
      "Bilgi ve İnanç",
      "İslam ve İbadet",
      "Ahlak ve Değerler",
      "Allah İnsan İlişkisi",
      "Hz. Muhammed (S.A.V.)",
      "Vahiy ve Akıl",
      "İslam Düşüncesinde Yorumlar, Mezhepler",
      "Din, Kültür ve Medeniyet",
      "İslam ve Bilim, Estetik, Barış",
      "Yaşayan Dinler",
    ],
  },
  Matematik: {
    name: "Matematik",
    totalQuestions: 40,
    icon: Calculator,
    bgClass: "bg-indigo-100 dark:bg-indigo-900/20",
    iconColor: "text-indigo-700 dark:text-indigo-300",
    topics: [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme",
      "EBOB – EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran Orantı",
      "Denklem Çözme",
      "Problemler",
      "Sayı Problemleri",
      "Kesir Problemleri",
      "Yaş Problemleri",
      "Hareket Hız Problemleri",
      "İşçi Emek Problemleri",
      "Yüzde Problemleri",
      "Kar Zarar Problemleri",
      "Karışım Problemleri",
      "Grafik Problemleri",
      "Rutin Olmayan Problemler",
      "Kümeler – Kartezyen Çarpım",
      "Mantık",
      "Fonksiyonlar",
      "Polinomlar",
      "2. Dereceden Denklemler",
      "Permütasyon ve Kombinasyon",
      "Olasılık",
      "Veri – İstatistik",
      "Temel Kavramlar",
      "Doğruda Açılar",
      "Üçgende Açılar",
      "Özel Üçgenler",
      "Dik Üçgen",
      "İkizkenar Üçgen",
      "Eşkenar Üçgen",
      "Açıortay",
      "Kenarortay",
      "Eşlik ve Benzerlik",
      "Üçgende Alan",
      "Üçgende Benzerlik",
      "Açı Kenar Bağıntıları",
      "Çokgenler",
      "Özel Dörtgenler",
      "Dörtgenler",
      "Deltoid",
      "Paralelkenar",
      "Eşkenar Dörtgen",
      "Dikdörtgen",
      "Kare",
      "Yamuk",
      "Çember ve Daire",
      "Çemberde Açı",
      "Çemberde Uzunluk",
      "Dairede Çevre ve Alan",
      "Analitik Geometri",
      "Noktanın Analitiği",
      "Doğrunun Analitiği",
      "Dönüşüm Geometrisi",
      "Katı Cisimler",
      "Prizmalar",
      "Küp",
      "Silindir",
      "Piramit",
      "Koni",
      "Küre",
      "Çemberin Analitiği",
    ],
  },
  Fizik: {
    name: "Fizik",
    totalQuestions: 7,
    icon: Atom,
    bgClass: "bg-teal-100 dark:bg-teal-900/20",
    iconColor: "text-teal-700 dark:text-teal-300",
    topics: [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Sıvıların Kaldırma Kuvveti",
      "Basınç",
      "Isı, Sıcaklık ve Genleşme",
      "Hareket ve Kuvvet",
      "Dinamik",
      "İş, Güç ve Enerji",
      "Elektrik",
      "Manyetizma",
      "Dalgalar",
      "Optik",
    ],
  },
  Kimya: {
    name: "Kimya",
    totalQuestions: 7,
    icon: FlaskConical,
    bgClass: "bg-lime-100 dark:bg-lime-900/20",
    iconColor: "text-lime-700 dark:text-lime-300",
    topics: [
      "Kimya Bilimi",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Doğa ve Kimya",
      "Kimyanın Temel Kanunları",
      "Kimyasal Hesaplamalar",
      "Karışımlar",
      "Asit, Baz ve Tuz",
      "Kimya Her Yerde",
    ],
  },
  Biyoloji: {
    name: "Biyoloji",
    totalQuestions: 6,
    icon: Trees,
    bgClass: "bg-fuchsia-100 dark:bg-fuchsia-900/20",
    iconColor: "text-fuchsia-700 dark:text-fuchsia-300",
    topics: [
      "Canlıların Ortak Özellikleri",
      "Canlıların Temel Bileşenleri",
      "Hücre ve Organelleri",
      "Hücre Zarından Madde Geçişi",
      "Canlıların Sınıflandırılması",
      "Mitoz ve Eşeysiz Üreme",
      "Mayoz ve Eşeyli Üreme",
      "Kalıtım",
      "Ekosistem Ekolojisi",
      "Güncel Çevre Sorunları",
    ],
  },
};
